spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: utuser
    password: utpassword
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
logging:
  level:
    root: info